apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: elastic
data:
  filebeat.yml: |
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          node: minikube  
          templates:
            - condition:
                contains:
                  kubernetes.container.name: "no-json-logging"
              config:
                - type: container
                  paths:
                    - "/var/log/containers/*-${data.kubernetes.container.id}.log"
            - condition:
                contains:
                  kubernetes.container.name: "json-logging"
              config:
                - type: container
                  paths:
                    - "/var/log/containers/*-${data.kubernetes.container.id}.log"
                  json.keys_under_root: true
                  json.add_error_key: true
                  json.message_key: message

    processors:
      - add_host_metadata: ~
      - add_cloud_metadata: ~
      - decode_json_fields:
          fields: ["message"]
          target: ""
          overwrite_keys: true

    output.elasticsearch:
      hosts: ["http://elasticsearch.elastic.svc.cluster.local:9200"]

    setup.kibana:
      host: "http://kibana.elastic.svc.cluster.local:5601"
