apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: elastic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-container
          image: busybox
          command: ['sh', '-c', 'while true; do echo "Hello World!"; sleep 5; done']
